---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: onsdigital/dp-concourse-tools-java

inputs:
  - name: dp-jwt-verifier-java

outputs:
  - name: build

run:
  path: dp-jwt-verifier-java/ci/scripts/build.sh
